#!/usr/bin/env ruby

require "steam/categorizer"
require "trollop"

opts = Trollop::options do
  opt :url_name, "Custom URL name set in Profile", :type=>:string, :required=>false
  opt :config, "Location of existing sharedconfig.vdf", :type=>:string, :required=>false
  opt :preferences, "Location of steam_categorizer preferences file", :type=>:string, :required=>false,
    :default=>"~/.config/steam_categorizer.json"
end

library = Steam::Categorizer::GameLibrary.new(
  url_name:opts[:url_name], preferences:opts[:preferences], shared_config:opts[:config])
library.collect_metadata()
library.map_categories()
steam_config = library.generate_steam_config()
library.export_steam_config()
